baseURL = 'https://ones.unfine.top/'
languageCode = 'zh-cn'
title = 'The ONES1.1'
theme = 'FixIt'


[pagination]
pagerSize = 10


[params]
  version = "0.3.X"
  description = "这是我的 Hugo FixIt 网站"
  keywords = ["Hugo", "FixIt"]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  enablePWA = true
  externalIcon = false
  capitalizeTitles = true
  withSiteTitle = true
  titleDelimiter = "-"
  indexWithSubtitle = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 3
    
[params.footer]
enable = true
copyright = true          # 不显示默认版权结构
customText = "© 2025 The ONES. All rights reserved."
since = "2025"

[params.footer.powered]
enable = false
hugoLogo = false
themeLogo = false
# ✅ 自定义作者信息（显示在“© 2025 作者名”中）
[params.author]
name = "The ONES. All rights reserved."
link = "https://ones.unifine.top"




[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[taxonomies]
  category = "categories"
  tag = "tags"
  collection = "collections"

[outputFormats]
  [outputFormats.Search]
    name = "search"
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "Search"]
