name: Deploy Hugo site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.5'
          extended: true

      - name: Cache Hugo resources
        uses: actions/cache@v3
        id: hugo-cache
        with:
          path: |
            ~/.cache/hugo
            resources/_gen
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.sum', '**/config.toml', '**/content/**') }}-v1
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Build site
        run: |
          hugo mod get
          hugo --minify
          ls -la ./public  

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          cname: ones.unifine.top
