name: Fetch TV List to /static/tv

on:
  schedule:
    - cron: '0 1 * * *'     # 每天 01:00 UTC（北京时间 09:00）自动执行
  workflow_dispatch:        # 可手动执行

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v3

      - name: 创建 static/tv 目录（如不存在）
        run: mkdir -p static/tv

      - name: 抓取接口内容
        run: |
          curl -s https://render-node-demo-6ijt.onrender.com/tvlist.txt -o static/tv/tvlistc.txt

      - name: 提交更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git pull --rebase  # ⭐️ 避免 push 被拒绝

          git add static/tv/tvlistc.txt
          git commit -m "每日更新 tvlist.txt：$(date -u)" || echo "没有变更"
          git push
