name: Fetch TV List to /static/tv

on:
  schedule:
    - cron: '0 1 * * *'     # 每天 01:00 UTC（北京时间 09:00）
  workflow_dispatch:        # 可手动触发

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # 确保拉取完整历史记录

      - name: 创建目录（如不存在）
        run: mkdir -p static/tv

      - name: 抓取接口内容
        run: |
          curl -s https://render-node-demo-6ijt.onrender.com/tvlist.txt -o static/tv/tvlistc.txt

      - name: 提交更新
        run: |
          # 配置 Git 身份
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 检查文件是否有变化（无变化则跳过提交）
          if git diff --quiet --exit-code; then
            echo "文件无变化，无需提交"
          else
            git add static/tv/tvlistc.txt
            git commit -m "自动更新 TV 列表: $(date -u '+%Y-%m-%d %H:%M:%S')"
            git pull --rebase origin main  # 先变基避免冲突
            git push origin main
          fi

      - name: 更新 gh-pages 分支的 tvlistc.txt
        run: |
          # 获取最新 gh-pages 分支
          git fetch origin gh-pages

          # 用 worktree 挂载 gh-pages 分支
          git worktree add gh-pages-dir gh-pages

          # 用新的 tvlistc.txt 覆盖 gh-pages 的文件
          cp static/tv/tvlistc.txt gh-pages-dir/tv/tvlistc.txt

          # 进入 gh-pages 目录并提交
          cd gh-pages-dir
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet --exit-code; then
            echo "gh-pages 中 tvlist 无变化，跳过提交"
          else
            git add tv/tvlistc.txt
            git commit -m "自动更新 gh-pages 中的 tvlistc.txt: $(date -u '+%Y-%m-%d %H:%M:%S')"
            git push origin gh-pages
          fi
    
